//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM_Program.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Japan_Msg_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Japan_Msg_Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLM_Program.Resources.Japan_Msg_Resource", typeof(Japan_Msg_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   内訳がキャンセルされました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳キャンセル中に誤り発生. プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳をキャンセルしますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳が削除されました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del {
            get {
                return ResourceManager.GetString("Msg_Base_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳削除中に誤り発生. プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳を削除しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最上端の保存ボタンを押してください。押さないとDBに反映されません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳が変更されました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit {
            get {
                return ResourceManager.GetString("Msg_Base_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳変更中にエラー発生。 プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Edit_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更内訳を保存しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Edit_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムを終了しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Exit_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Exit_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳転換中に誤り発生. プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Export_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Export_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業の内訳が保存されました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Export_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Export_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳が保存されました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳保存中に誤り発生. プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Save_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい内訳を保存しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Save_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内訳照会中に誤り発生. プログラム業者に問い合わせしてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Select_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Select_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現内訳と関連したデータが存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Connect_Data {
            get {
                return ResourceManager.GetString("Msg_Connect_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修正時、２件以上入力できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Edit_Two_Not {
            get {
                return ResourceManager.GetString("Msg_Edit_Two_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクセル転換できる使用者権限がありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Excel_Not_TF {
            get {
                return ResourceManager.GetString("Msg_Excel_Not_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大分類コードを選択してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Goods_Sort_1 {
            get {
                return ResourceManager.GetString("Msg_Goods_Sort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中分類コードを選択してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Goods_Sort_2 {
            get {
                return ResourceManager.GetString("Msg_Goods_Sort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修正の場合、同時に入力が不可能です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Input_Same_Not {
            get {
                return ResourceManager.GetString("Msg_Input_Same_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更作業の時、コードは変更できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Key_Not_Change {
            get {
                return ResourceManager.GetString("Msg_Key_Not_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しない使用者IDです。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_ID {
            get {
                return ResourceManager.GetString("Msg_Login_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに接続されている使用者IDです。 接続不可能です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_ID_2 {
            get {
                return ResourceManager.GetString("Msg_Login_ID_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが一致しません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_PW {
            get {
                return ResourceManager.GetString("Msg_Login_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中止会員を新しい上位に指定できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Delete_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Delete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本人下位グループに属した会員を新しい上位に指定できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい上位に指定された会員のダウン内訳がプールです。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Full {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい上位が以前と同一です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Same {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい上位に本人を指定できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Self {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   脱退会員を上位に指定できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Leave_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Leave_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   脱退会員は購入できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Leave_Sell {
            get {
                return ResourceManager.GetString("Msg_Mem_Leave_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員番号自動生成の場合は推薦者を必ず入力しなければなりません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Auto_Nomin {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Auto_Nomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最上位チェックされた場合、会員番号を自動にできません。 手動チェック後、番号を直接入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Auto_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Auto_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員番号手動入力選択. 会員番号未入力状態. 自動で生成しましょうか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Hand_Not_Q {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Hand_Not_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手動で入力された会員番号はすでに使用中です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単純消費者を上位に指定できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Sell_TF_0 {
            get {
                return ResourceManager.GetString("Msg_Mem_Sell_TF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最上位選択状態で上位会員コードが入力されています。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Up_Checked {
            get {
                return ResourceManager.GetString("Msg_Mem_Up_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに同一Web IDが存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Webid_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Webid_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後援者も推薦者と同一ですか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Nom_Same_Save_Q {
            get {
                return ResourceManager.GetString("Msg_Nom_Same_Save_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   締め切り精算された日付です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Close_Date {
            get {
                return ResourceManager.GetString("Msg_Not_Close_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除不可能な使用者IDです。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Del_UserID {
            get {
                return ResourceManager.GetString("Msg_Not_Del_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用者お気に入りメニューは20個を超えられません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_FarMenu_20 {
            get {
                return ResourceManager.GetString("Msg_Not_FarMenu_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された内訳がありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input {
            get {
                return ResourceManager.GetString("Msg_Not_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力された内訳に誤りがあります。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Err {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索日付を必ず入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_SDate {
            get {
                return ResourceManager.GetString("Msg_Not_Input_SDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常内訳です。 現画面では修正/キャンセルできません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_01 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現内訳は返品/部分返品/交換が発生した内訳です。 修正/キャンセルできません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_1 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体返品内訳です。 現画面では修正/キャンセルできません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_2 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分返品内訳です。 現画面では修正/キャンセルできません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_3 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   交換内訳です。 現画面では修正/キャンセルできません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_4 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された内訳がありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select {
            get {
                return ResourceManager.GetString("Msg_Not_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された内訳中に数量0の内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select_0 {
            get {
                return ResourceManager.GetString("Msg_Not_Select_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お問い合わせ内訳を入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select_Term {
            get {
                return ResourceManager.GetString("Msg_Not_Select_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認後、もう一度試みてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Re_Action {
            get {
                return ResourceManager.GetString("Msg_Re_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択後、もう一度試みてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Re_Select {
            get {
                return ResourceManager.GetString("Msg_Re_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須要素を入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Requisite_Data {
            get {
                return ResourceManager.GetString("Msg_Requisite_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに同一コードが存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Same_Code {
            get {
                return ResourceManager.GetString("Msg_Same_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに同一名称が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Same_Name {
            get {
                return ResourceManager.GetString("Msg_Same_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダに内訳が保存されました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Save_Folder {
            get {
                return ResourceManager.GetString("Msg_Save_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現注文と関連した返品内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_2 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現注文と関連した部分返品内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_3 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現注文と関連した交換内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_4 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購入キャンセルできる使用者権限がありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_Not_TF {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_Not_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに返品された内訳です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体返品された内訳です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   払い戻し日付が元販売決済日以前です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_001 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品関連払い戻し内訳や元注文関連決済内訳の内から選択後.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_002 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品関連払い戻し内訳選択後.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_003 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   払い戻し額で入力した金額が元販売決済金額より多いです。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_004 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残りの返品使用可能数量がありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_003 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品する数量が使用可能数量より大きくなれません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_004 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未成年者は登録できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_19 {
            get {
                return ResourceManager.GetString("Msg_SN_Number_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業者番号を正しく入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Error {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業者番号は必須入力事項です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Put {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業者番号で重複加入が不可能です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Same {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_AddCode {
            get {
                return ResourceManager.GetString("Msg_Sort_AddCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   事業者番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_BuNum {
            get {
                return ResourceManager.GetString("Msg_Sort_BuNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現金決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現金/無通帳決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現金/カード決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無通帳決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カード/無通帳決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_2_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カード決済金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   払い戻し金額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_R {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センター과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更適用日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_ChangDate {
            get {
                return ResourceManager.GetString("Msg_Sort_ChangDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに選択された内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Check {
            get {
                return ResourceManager.GetString("Msg_Sort_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手当て精算과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Close {
            get {
                return ResourceManager.GetString("Msg_Sort_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Count {
            get {
                return ResourceManager.GetString("Msg_Sort_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cpno {
            get {
                return ResourceManager.GetString("Msg_Sort_Cpno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファックス番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Fax {
            get {
                return ResourceManager.GetString("Msg_Sort_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上位区分과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   大分類과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort_1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中分類과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自宅電話番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_HomeTel {
            get {
                return ResourceManager.GetString("Msg_Sort_HomeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   携帯電話番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Hptel {
            get {
                return ResourceManager.GetString("Msg_Sort_Hptel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入庫과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_InPut {
            get {
                return ResourceManager.GetString("Msg_Sort_InPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員後援位置과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_LineCnt {
            get {
                return ResourceManager.GetString("Msg_Sort_LineCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員名과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_M_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_M_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Mem {
            get {
                return ResourceManager.GetString("Msg_Sort_Mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_MemNumber {
            get {
                return ResourceManager.GetString("Msg_Sort_MemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫移動과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Move {
            get {
                return ResourceManager.GetString("Msg_Sort_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会員推薦位置과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_N_LineCnt {
            get {
                return ResourceManager.GetString("Msg_Sort_N_LineCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   推薦者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Nomin {
            get {
                return ResourceManager.GetString("Msg_Sort_Nomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更不可能과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Not_Chang {
            get {
                return ResourceManager.GetString("Msg_Sort_Not_Chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出庫과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_OutPut {
            get {
                return ResourceManager.GetString("Msg_Sort_OutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   買入先과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Purchase {
            get {
                return ResourceManager.GetString("Msg_Sort_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購買商品配送과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Rece {
            get {
                return ResourceManager.GetString("Msg_Sort_Rece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後援者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Save {
            get {
                return ResourceManager.GetString("Msg_Sort_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注文番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_OrderNumber {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総購買額과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_Price {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総購買PV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_PV {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売センター과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellCenter {
            get {
                return ResourceManager.GetString("Msg_Sort_SellCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購買種類과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellCode {
            get {
                return ResourceManager.GetString("Msg_Sort_SellCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   購買日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate_Re {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返品日が購買日より前です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate_ReDate_Er {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate_ReDate_Er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入庫先과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_In_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_In_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入庫日과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_In_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_In_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入庫理由과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_IN_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_IN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動日付과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Move_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Move_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出庫先과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Out_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Out_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出庫日付과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Out_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Out_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された内訳中にすでに出庫された内訳が存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Pre {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Tel {
            get {
                return ResourceManager.GetString("Msg_Sort_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電話番号과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Tel1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用者ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_ID {
            get {
                return ResourceManager.GetString("Msg_Sort_User_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用者名前과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用者パスワード과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用者パスワード確認과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードとパスワード確認欄に入力した内訳が不一致です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password_Not {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入庫情報が存在する内訳です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Stock_IN {
            get {
                return ResourceManager.GetString("Msg_Stock_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出庫情報が存在する内訳です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Stock_Out {
            get {
                return ResourceManager.GetString("Msg_Stock_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードをケタ数に合わせて入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_txt_Not_Code {
            get {
                return ResourceManager.GetString("Msg_txt_Not_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄です。 内訳を入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_txt_Not_Data {
            get {
                return ResourceManager.GetString("Msg_txt_Not_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現資料を使用中のデータが存在します。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Data {
            get {
                return ResourceManager.GetString("Msg_Useing_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更された位置は、現在他の会員様の位置です。 位置を互いに変更しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line {
            get {
                return ResourceManager.GetString("Msg_Useing_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン中止は職のままに推薦または、後援した会員がない場合にだけ可能です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Down {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン中止は脱退後可能です。 脱退処理を先に保存された後にライン中止をしてくれてください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Leave {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更された位置は使うことはできない位置値です。 最大値を越えました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更された位置は、現在他の会員様の位置です。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not_2 {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン中止を解除する場合、その位置を獲得できません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not_3 {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライン中止を解除する場合、位置値を0以上に入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Re_Using {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Re_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更選択された内訳が空欄です。 空欄の内訳を適用しますか?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Not_Data {
            get {
                return ResourceManager.GetString("Msg_Useing_Not_Data", resourceCulture);
            }
        }
    }
}
