//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM_Program.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class US_Msg_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal US_Msg_Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLM_Program.Resources.US_Msg_Resource", typeof(US_Msg_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   History view was cancelled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error whle History view cancel. Please contact development vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure that you want to cancel? 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Cancel_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Cancel_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History was deleted 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del {
            get {
                return ResourceManager.GetString("Msg_Base_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while deleting history.  Please contact develop vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure that you want to delete?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make sure you click the &quot;Save&quot; button at the top to commit your changes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Del_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Del_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change was committed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit {
            get {
                return ResourceManager.GetString("Msg_Base_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while changing, Please contact development vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Edit_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you save your change?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Edit_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Edit_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you terminate the program?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Exit_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Exit_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while changing, Please contact development vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Export_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Export_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your job was saved!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Export_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Export_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job was saved!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save {
            get {
                return ResourceManager.GetString("Msg_Base_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while saving, Please contact development vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Save_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save ? 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Save_Q {
            get {
                return ResourceManager.GetString("Msg_Base_Save_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error while inquiry. Please contact development vendor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Select_Err {
            get {
                return ResourceManager.GetString("Msg_Base_Select_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The requested operation has been completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Base_Work_End {
            get {
                return ResourceManager.GetString("Msg_Base_Work_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a data related with this.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Connect_Data {
            get {
                return ResourceManager.GetString("Msg_Connect_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In case of edit, It is not allowed to  two data simultaneously.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Edit_Two_Not {
            get {
                return ResourceManager.GetString("Msg_Edit_Two_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Require a Excel conversion authority.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Excel_Not_TF {
            get {
                return ResourceManager.GetString("Msg_Excel_Not_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select lage scale classification code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Goods_Sort_1 {
            get {
                return ResourceManager.GetString("Msg_Goods_Sort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select medium scale classification code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Goods_Sort_2 {
            get {
                return ResourceManager.GetString("Msg_Goods_Sort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In case of edit, It is not allowed to  two data simultaneously.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Input_Same_Not {
            get {
                return ResourceManager.GetString("Msg_Input_Same_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code change not allowed while modification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Key_Not_Change {
            get {
                return ResourceManager.GetString("Msg_Key_Not_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID does not existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_ID {
            get {
                return ResourceManager.GetString("Msg_Login_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID already accessed to the system, Please check your ID or contact customer center. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_ID_2 {
            get {
                return ResourceManager.GetString("Msg_Login_ID_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   your password do not match 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Login_PW {
            get {
                return ResourceManager.GetString("Msg_Login_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped distributor does not allowed to assign as a new up-line.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Delete_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Delete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not place your down-line as a up-line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign sponsor&apos;s down-Line is full, please assign new one as asponsor 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Full {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New up-line is same as previous과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Same {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not be assigned as a new upline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Down_Self {
            get {
                return ResourceManager.GetString("Msg_Mem_Down_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted distributor can not be assign as a up-line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Leave_ {
            get {
                return ResourceManager.GetString("Msg_Mem_Leave_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted distributor can not place an order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Leave_Sell {
            get {
                return ResourceManager.GetString("Msg_Mem_Leave_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommender ID is required if distributor number is generated automatically.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Auto_Nomin {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Auto_Nomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In case of checked as a top level distributor, distributor number can not be generated automatically. Please check manual input and enter number directly. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Auto_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Auto_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select distributor number manual input, Distributor number does not entered. Do you want to generate the number automatically? 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Hand_Not_Q {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Hand_Not_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual input distributor number already existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Mbid_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Mbid_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Customer can not be assigned as a Up-Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Sell_TF_0 {
            get {
                return ResourceManager.GetString("Msg_Mem_Sell_TF_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up-Line distributor number was entered in the status of top level selection.  과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Up_Checked {
            get {
                return ResourceManager.GetString("Msg_Mem_Up_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same WEB ID is existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Mem_Webid_Not {
            get {
                return ResourceManager.GetString("Msg_Mem_Webid_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sponsor and recommender is same?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Nom_Same_Save_Q {
            get {
                return ResourceManager.GetString("Msg_Nom_Same_Save_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settlement closed date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Close_Date {
            get {
                return ResourceManager.GetString("Msg_Not_Close_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This User ID can not be deleted 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Del_UserID {
            get {
                return ResourceManager.GetString("Msg_Not_Del_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of user bookmark can not be exceded over 20 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_FarMenu_20 {
            get {
                return ResourceManager.GetString("Msg_Not_FarMenu_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No entry data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input {
            get {
                return ResourceManager.GetString("Msg_Not_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invailed entry data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Err {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search date required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_SDate {
            get {
                return ResourceManager.GetString("Msg_Not_Input_SDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal data, Edit/Cancel is not allowed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_01 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current data is from the Return/Partial return/Exchange, Edit/Cancel is not allowed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_1 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total return history, Edit/Cancel is not allowed in this screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_2 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Partial Return history, Edit/Cancel is not allowed in this screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_3 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exchange history, Edit/Cancel is not allowed in this screen.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Input_Sell_4 {
            get {
                return ResourceManager.GetString("Msg_Not_Input_Sell_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select {
            get {
                return ResourceManager.GetString("Msg_Not_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a data that quantity is &quot;0&quot; in your selection criteria. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select_0 {
            get {
                return ResourceManager.GetString("Msg_Not_Select_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input inquiry item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Not_Select_Term {
            get {
                return ResourceManager.GetString("Msg_Not_Select_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check it and try again!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Re_Action {
            get {
                return ResourceManager.GetString("Msg_Re_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select it and try again!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Re_Select {
            get {
                return ResourceManager.GetString("Msg_Re_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input required item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Requisite_Data {
            get {
                return ResourceManager.GetString("Msg_Requisite_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same code is existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Same_Code {
            get {
                return ResourceManager.GetString("Msg_Same_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same name is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Same_Name {
            get {
                return ResourceManager.GetString("Msg_Same_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data was saved to the Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Save_Folder {
            get {
                return ResourceManager.GetString("Msg_Save_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current order related return is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_2 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current order related partial return is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_3 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current order related exchange is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_4 {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry, you are not authorized to cancel this order.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Del_Not_TF {
            get {
                return ResourceManager.GetString("Msg_Sell_Del_Not_TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returned item view 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All returned item view.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: Refund date is prior to Order payment date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_001 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After selection of  return refund or original order payment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_002 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After selection of  return refund과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_003 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: Refund amount is grater than Order amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_002_004 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_002_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No available return quantity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_003 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: Return auantity is grater than Order quantity 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sell_Return_Re_004 {
            get {
                return ResourceManager.GetString("Msg_Sell_Return_Re_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minor can not enroll as a Distributor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_19 {
            get {
                return ResourceManager.GetString("Msg_SN_Number_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invailed resident number or business Entity Number, Please verify it and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Error {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resident number or business Entity Number is required과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Put {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alredy registered resident number or business Entity Number, Please verify it and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SN_Number_Same {
            get {
                return ResourceManager.GetString("Msg_SN_Number_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Postal Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_AddCode {
            get {
                return ResourceManager.GetString("Msg_Sort_AddCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Business Entity Number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_BuNum {
            get {
                return ResourceManager.GetString("Msg_Sort_BuNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cash payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cash/Direct Debit payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cash/Credit card payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_1_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direct Debit payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Card/Direct Debit payment number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_2_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Card Payment Amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_3 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDC Payment amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_7 {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refund amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cacu_Price_R {
            get {
                return ResourceManager.GetString("Msg_Sort_Cacu_Price_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change apply date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_ChangDate {
            get {
                return ResourceManager.GetString("Msg_Sort_ChangDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected item is already existed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Check {
            get {
                return ResourceManager.GetString("Msg_Sort_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bonus settlement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Close {
            get {
                return ResourceManager.GetString("Msg_Sort_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quantity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Count {
            get {
                return ResourceManager.GetString("Msg_Sort_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resident Number 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Cpno {
            get {
                return ResourceManager.GetString("Msg_Sort_Cpno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fax: 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Fax {
            get {
                return ResourceManager.GetString("Msg_Sort_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper level glaf과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lage scale classification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort_1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium scale classification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Goods_Sort_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_Goods_Sort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home Phone:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_HomeTel {
            get {
                return ResourceManager.GetString("Msg_Sort_HomeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mobile Phone:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Hptel {
            get {
                return ResourceManager.GetString("Msg_Sort_Hptel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_InPut {
            get {
                return ResourceManager.GetString("Msg_Sort_InPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributor sponsor placement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_LineCnt {
            get {
                return ResourceManager.GetString("Msg_Sort_LineCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributor Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_M_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_M_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Mem {
            get {
                return ResourceManager.GetString("Msg_Sort_Mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributor Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_MemNumber {
            get {
                return ResourceManager.GetString("Msg_Sort_MemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory Movement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Move {
            get {
                return ResourceManager.GetString("Msg_Sort_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distributor recommender placement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_N_LineCnt {
            get {
                return ResourceManager.GetString("Msg_Sort_N_LineCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recommender 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Nomin {
            get {
                return ResourceManager.GetString("Msg_Sort_Nomin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change not availble.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Not_Chang {
            get {
                return ResourceManager.GetString("Msg_Sort_Not_Chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shipment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_OutPut {
            get {
                return ResourceManager.GetString("Msg_Sort_OutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supplier과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Purchase {
            get {
                return ResourceManager.GetString("Msg_Sort_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purchase order shipment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Rece {
            get {
                return ResourceManager.GetString("Msg_Sort_Rece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sponsor 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Save {
            get {
                return ResourceManager.GetString("Msg_Sort_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sale과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_OrderNumber {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total order amount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_Price {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Order PV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Sell_PV {
            get {
                return ResourceManager.GetString("Msg_Sort_Sell_PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distribution Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellCenter {
            get {
                return ResourceManager.GetString("Msg_Sort_SellCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellCode {
            get {
                return ResourceManager.GetString("Msg_Sort_SellCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retun date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate_Re {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate_Re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: Return date is prior to Order date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_SellDate_ReDate_Er {
            get {
                return ResourceManager.GetString("Msg_Sort_SellDate_ReDate_Er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instock Place과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_In_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_In_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instock date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_In_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_In_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instock reason과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_IN_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_IN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movement date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Move_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Move_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shipping place과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Out_Center {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Out_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shipping date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Out_Date {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Out_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: some of you selected items were already shipped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Stock_Pre {
            get {
                return ResourceManager.GetString("Msg_Sort_Stock_Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Tel {
            get {
                return ResourceManager.GetString("Msg_Sort_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phone number:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_Tel1 {
            get {
                return ResourceManager.GetString("Msg_Sort_Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_ID {
            get {
                return ResourceManager.GetString("Msg_Sort_User_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Name {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Password:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm User Password:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password_2 {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password does not match 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Sort_User_Password_Not {
            get {
                return ResourceManager.GetString("Msg_Sort_User_Password_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Instock information is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Stock_IN {
            get {
                return ResourceManager.GetString("Msg_Stock_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shipping information is existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Stock_Out {
            get {
                return ResourceManager.GetString("Msg_Stock_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Langth of code is not correct, please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_txt_Not_Code {
            get {
                return ResourceManager.GetString("Msg_txt_Not_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required field, please input 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_txt_Not_Data {
            get {
                return ResourceManager.GetString("Msg_txt_Not_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note: Data is used by another user.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Data {
            get {
                return ResourceManager.GetString("Msg_Useing_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The position is occupied by other  distributor. Do you want to exchange it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line {
            get {
                return ResourceManager.GetString("Msg_Useing_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line stop is only available if there is no recommender or sponsor only.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Down {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line stop is available only after distributor resign. Please do line stop after delete distributor 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Leave {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position value is not available. It was over the maximum value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changing position was occupied by other distributor 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not_2 {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if release the line stop, Position is not available 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Not_3 {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Not_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    if release the line stop, Please input Position value greater than &quot;0&quot;. 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Line_Re_Using {
            get {
                return ResourceManager.GetString("Msg_Useing_Line_Re_Using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected change field remains as  blank, Do you want to apply it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Useing_Not_Data {
            get {
                return ResourceManager.GetString("Msg_Useing_Not_Data", resourceCulture);
            }
        }
    }
}
